workspace:
  base: /go
  path: src/git.target.com/MattClark/drone-plugin-test
pipeline:
  build:
    image: golang
    commands:
      - go build
  publish:
    gh_pages:
      image: plugins/drone-gh-pages
      source: docs
      remote: origin
